//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyForumEntities : DbContext
    {
        public MyForumEntities()
            : base("name=MyForumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanKuai> BanKuai { get; set; }
        public virtual DbSet<Partition> Partition { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<TieZi> TieZi { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
